# VER?TABANI BA?LANTISI
spring.datasource.url=jdbc:postgresql://localhost:5432/GorevYonetimSistemi
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# PORT (HTTPS için genelde 8443 veya 443 kullan?l?r)
server.port=8443

# SSL/TLS AYARLARI
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=spring-boot

# GÜVENL?K: Sadece HTTPS üzerinden Cookie gönderilsin
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
